### ISSUE TITLE
bug report test

### ISSUE THREAD

**Issue by Ru-bixcube** [labsyspharm/minerva-story#1]
Detailed description of bug here.

Can included code:
```
> code here
```

And even attach images:
<img width="1199" alt="Screen Shot 2020-03-20 at 7 29 55 PM" src="https://user-images.githubusercontent.com/31513137/77213520-774de180-6ae1-11ea-9add-2c1a56d93aec.png">

**Comment by kruegert** [comment]
![image](https://user-images.githubusercontent.com/31503434/77559428-91494480-6e92-11ea-9629-bc0681c115f0.png)
Test
