### ISSUE TITLE
Clarify csv input minerva author

### ISSUE THREAD

**Issue by rjp21** [labsyspharm/minerva-story#18]
There are two fields for input on the start page, one indicates to put the full path (to the image file) but the next does not specify full path (to the csv file) though it too requires the user to input the full file-path. It could lead to user frustration if there is any ambiguity here. I think it should be noted that the full path is required for both files.

**Comment by Ru-bixcube** [comment]
Hi rjp21, we will add a file browser option in the new version so users will no longer have to copy and paste file paths.
