### ISSUE TITLE
Save button

### ISSUE THREAD

**Issue by janaed** [labsyspharm/minerva-story#19]
Noticed that the **Save** button doesn't instantaneously save edits. Would recommend that the user track the time stamps in the terminal window or `out.yaml` file to ensure that the most recent changes are saved before closing **Minerva Demo** in the web browser.

**Comment by Juha-Ruokonen** [comment]
We should show a spinner / progress bar in the UI, while the tiles are being rendered and saved to disk, and show a notification after everything has completed.
