### ISSUE TITLE
Safari Integration

### ISSUE THREAD

**Issue by edn314** [labsyspharm/minerva-story#21]
Image data cannot be uploaded to an Apple Safari web browser. This may be a nice feature to include or the tutorial should mention Minerva Author is optimized for Google Chrome.

**Comment by Ru-bixcube** [comment]
Hi edn314, we have edited the wiki documentation to communicate this.
https://github.com/labsyspharm/minerva-story/wiki/How-to-make-a-Minerva-Story%3F
