### ISSUE TITLE
Adding "New Channel Group" Button

### ISSUE THREAD

**Issue by edn314** [labsyspharm/minerva-story#22]
It would be helpful to have a "new channel group" button.  Otherwise the user has to overwrite the existing channel group name to create a new channel.  This may not be intuitive for some users.

**Comment by edn314** [comment]
Additionally, currently existing channels with default intensities are populated into the new channel group.  Would be helpful to either have the modified channel intensities carry over into the new channel group or to have a new channel group created without any existing channels.

**Comment by DanaeA** [comment]
I agree with this comment, and would prefer for when opening a new channel group for it to be blank. But even if it has the channels I had just worked with, it makes more sense for resetting the default intensities for a new channel group.

**Comment by Ru-bixcube** [comment]
Please add this button by making the first row of the drop down menu say "Create New Channel Group"

When a new channel group is created, please let the default setting be blank as preferred by the user group
