### ISSUE TITLE
adding a sample name in Minerva Author

### ISSUE THREAD

**Issue by tuuliavallius** [labsyspharm/minerva-story#23]
Would be great help to keep track of the created stories, if somewhere in the yml file you could actually see the sample name, in order to avoid confusion.

Also, would like to add the descriptive text of the sample (=header) during the Minerva Author phase. At the current version, you need to add the header text to the yml file. Interestingly, Header means description of the sample and Description means Title/header. Would be more intuitive to swap these.

**Comment by Ru-bixcube** [comment]
Please have the user input this on the data import page and be recorded in the "Description" field under "Image" in the YAML file. That way it will appear in the location indicated by the red box in the image below

<img width="375" alt="Screen Shot 2020-04-03 at 4 34 01 PM" src="https://user-images.githubusercontent.com/31513137/78402808-42558a80-75c9-11ea-9cda-d1bd1f11fae7.png">

**Comment by Juha-Ruokonen** [comment]
Would it make more sense to have the description field somewhere in "Edit Story" page? I was thinking that there's no navigation back to import page, and thus the user can not edit the description once set.

**Comment by Ru-bixcube** [comment]
Sure! That would make sense. Feel free to rename the "Description" field in the yaml to "Title" if that is more intuitive/not too much of a hassle.

Right now, the purpose of this field is to give the dataset a title in the Minerva Story browser. But in the future, we may also want to include the string in this field in the "out" folder name and yaml file name when exporting from Author. That way, if a user processes multiple samples, the outputs do not get mixed up. If aiming for the latter goal, this field needs to have an input by the user before the first time they hit save.
