### ISSUE TITLE
Channel Names

### ISSUE THREAD

**Issue by claireritch96** [labsyspharm/minerva-story#26]
Although there is a way to adjust the channel name when you are rendering it, there should be a way to change the channel name in the actual drop down menu. Right now the only option you have to change the basic channel name in the dropdown menu is to import a different csv file.

**Comment by Ru-bixcube** [comment]
Hi claireritch96, there is a way to change the channel name by editing the text in the field boxed in red (image below). We predict editing in this field will lead to fewer errors and accidental channel mixups for users than editing in the drop down menu.

<img width="400" alt="78614304-358c9d00-783c-11ea-9a2d-24a3e10ea9c2" src="https://user-images.githubusercontent.com/31513137/78908603-54fc1380-7a50-11ea-9f4d-0cef464aaba2.png">

**Comment by claireritch96** [comment]
Yes, I am aware of this feature which is why I originally alluded to it in
my thread. However, in the event, that your channels are mixed up from your
Ome.tif or your excel file, then you have to either A. Keep reimporting
files to correct the dropdown menu which I think is unnecessary and clunky
for Minerva Author or B. Edit the name every time you want to use that
channel for making a new group which is both tedious and potentially
confusing for the user. Alternatively, you could include a feature where
you could edit the dropdown, but you have to click a save button to enable
those changes.  This would both prevent accidentally changing names and
prevent someone from having to change the name every time they add it to a
new group.

**Comment by Ru-bixcube** [comment]
Hi claireritch96, I am trying to understand your reported issue better. When you edit the channel name using the text field in the image above, does the channel name displayed in the drop down menu not update?

**Comment by claireritch96** [comment]
Nevermind. I was mistaken. It's a non-issue. When I change the channel name
in the rendering settings, it automatically carries over to the dropdown
which is similar to how you update channels in Omero.
