### ISSUE TITLE
Clustergram scaling

### ISSUE THREAD

**Issue by DanaeA** [labsyspharm/minerva-story#36]
I've inserted a clustering diagram, where positive represents expression of a marker. However, the colors are inverted and low expression is a brighter color (the opposite of what I would expect). How can I change this? 

I've attached a photo for reference:
![image](https://user-images.githubusercontent.com/62964247/78935122-1ed38980-7a7a-11ea-80d4-cb98be1d838f.png)

**Comment by kruegert** [comment]
This is now possible.
The matrix can either be specified the old way:

### The old way:
VisMatrix: /assets/visdata/clust7hpdat_LUNG-3-PR.csv

### Or the new way:
      VisMatrix:
        data: /assets/visdata/clust7hpdat_LUNG-3-PR.csv
        colormapInvert: true
        colorTicks: 8

#### data
Specifies the data location

#### colormapInvert
`colormapInvert: false` specifies to have a bright color for low expression and dark color for high explression
`colormapInvert: true` specifies to have a dark color for low expression and bright color for high explression

#### Ticks
The number of bins/ticks of the discrete colormap can be set between 3 and 9. All other values will be up or downgraded to 9 or 3 respectively.
