### ISSUE TITLE
Add explanation to readme of repo organization

### ISSUE THREAD

**Issue by sofroniewn** [labsyspharm/minerva-story#65]
As part of my review for https://github.com/openjournals/joss-reviews/issues/2579, I think this readme could also contain an additional explanation of the repository organization - maybe something along the lines of this comment https://github.com/openjournals/joss-reviews/issues/2579#issuecomment-679235692 and a reference to `minerva-browser` in particular https://github.com/labsyspharm/minerva-browser. You could in fact write a generic portion of the readme that could be reused on all the related repos indicating their interconnectedness. This could help a new contributor get oriented in the project.

**Comment by thejohnhoffer** [comment]
Hi @sofroniewn,

I've added the snippet from that review comment to all four of the Minerva README.md files.

Thanks,
John

**Comment by sofroniewn** [comment]
Great! I think this can now be closed
